config/routes.rb
Rails.application.routes.draw do
  resources :shops
  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    'registrations': 'users/registrations'
  }
  root to: 'shops#show_shops'
  get 'show_shops', to: 'shops#show_shops'
  get 'search', to: 'shops#search'
  post 'send_email/:id', to: 'shops#send_email', as: 'send_email'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user, optional: true
  has_many :categories, dependent: :destroy

  validates :shop_name, :description, presence: true
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

# require_dependency 'app/services/shop_saver.rb'

class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy send_email]
  before_action :set_current_user_shops, only: %i[index]

  # GET /shops or /shops.json
  def index
    authorize @shops
  end

  # GET /shops/1 or /shops/1.json
  def show
    authorize @shop
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    authorize @shop
  end

  # GET /shops/1/edit
  def edit
    authorize @shop
  end

  # POST /shops or /shops.json
  def create
    params = shop_params
    @shop = Shop.new(shop_name: params[:shop_name], description: params[:description])
    authorize @shop
    @shop.user_id = current_user.id
    respond_to do |format|
      if @shop.save
        flag = ShopCategory.new.save_categories(@shop, params[:category])
        notice = if flag
                   'Shop was successfully saved.'
                 else
                   'Shop was successfully saved, but some services could not be added'
                 end
        format.html { redirect_to @shop, notice: notice }
        format.json { render :show, status: :created, location: @shop }
      else
        # @shop.errors.add(:category, 'not saved')
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    authorize @shop
    params = shop_params
    respond_to do |format|
      if @shop.update(shop_name: params[:shop_name], description: params[:description])
        shop_category = ShopCategory.new
        shop_category.delete_old_categories(@shop)
        flag = shop_category.save_categories(@shop, params[:category])
        notice = if flag
                   'Shop was successfully updated.'
                 else
                   'Shop was successfully updated, but services could not be added'
                 end
        format.html { redirect_to @shop, notice: notice }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    authorize @shop
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_shops
    @shops = Shop.all
    authorize @shops
  end

  def search
    @shops = ShopCategory.new.search_shops(params[:query])
    render 'show_shops'
  end

  def send_email
    ShopMailer.with(shop: @shop).mail_shopper.deliver_later
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def set_current_user_shops
    @shops = Shop.where(user_id: current_user.id)
  end

  # Only allow a list of trusted parameters through.
  def shop_params
    params.fetch(:shop, {})
    params.require(:shop).permit(:shop_name, :description, category: [])
  end
end

app/helpers/shops_helper.rb
# frozen_string_literal: true

module ShopsHelper
  def select_categories
    services = Category.services.keys
    services.map { |s| [s.gsub('_', ' ').capitalize, s] }
  end
end

app/views/shops/_form.html.erb
<%= form_with(model: [shop]) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>
      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= form.label :shop_name %>
    <%= form.text_field :shop_name %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>

  <% if shop.categories.any? %>
    <p>
      <strong>Categories for this shop:</strong>
      <% shop.categories.each do |cat| %>
        <span><%= cat.service %> / </span>
      <% end %>
    </p>
  <% end %>

  <p>
    <%= form.label :category %>
    <%= form.select(:category, select_categories, { prompt: "Please select below categories" },
                    { multiple: true }
        ) %>
  </p>

  <%#= form.collection_select(:language_ids, Language.all, :id, :name,{}, {:multiple => true}) %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
  <tr>
    <th>Shop Name</th>
    <th>Description</th>
    <th>
      Categories List
    </th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @shops.each do |shop| %>
    <tr>
      <td><%= shop.shop_name %></td>
      <td><%= shop.description %></td>
      <td>
        <% if shop.categories.any? %>
          <% shop.categories.each do |cat| %>
            <span><%= cat.service %> / </span>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to 'Show', shop %></td>
      <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
      <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop Name</strong>
  <%= @shop.shop_name %>
</p>

<p>
  <strong>Description</strong>
  <%= @shop.description %>
</p>

<% if @shop.categories.any? %>
  <p>
    <strong>Categories for this shop:</strong>
    <% @shop.categories.each do |cat| %>
      <span><%= cat.service %> / </span>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>

app/views/shops/show_shops.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<%= form_with url: '/search', method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Shop Name</th>
    <th>Description</th>
    <th>
      Categories List
    </th>
  </tr>
  </thead>

  <tbody>

  <% @shops.each do |shop| %>
    <tr>
      <td><%= shop.shop_name %></td>
      <td><%= shop.description %></td>
      <td>
        <% if shop.categories.any? %>
          <% shop.categories.each do |cat| %>
            <span><%= cat.service %> / </span>
          <% end %>
        <% end %>
      </td>
      <td> <%= button_to 'Contact', send_email_path(shop) %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if policy(@shops).index? %>
  <%= link_to 'Shops index', shops_path %>
<% end %>